monitor:
  resolution: [1024, 768]
  distance_cm: 60
  width_cm: 50
  refresh_rate_hz: 60.01

display:
  color_rgb255: [110, 110, 110]
  fullscreen: true
  screen_index: 0
  use_gui: true
  color_space: "rgb255"
  flip_interval_override: 0.0

sync:
  method: "none"
  ttl_port: "/dev/ttyUSB0"
  lsl_stream_name: "luminance"