experiment:
  name: "{{ cookiecutter.experiment }}"
  author: "{{ cookiecutter.author_name }}"
  description: "{{ cookiecutter.description }}"
  version: "{{ cookiecutter.version }}"
  created: "{{ cookiecutter._template_context_cookiecutter.creation_date | default('2025-04-18') }}"
  uuid: "{{ cookiecutter._template_context_cookiecutter.experiment_id | default('autogen') }}"

hardware:
  use_pupil_core: "{{ cookiecutter.use_pupil_core | default('yes') }}"
  use_pupil_neo: "{{ cookiecutter.use_pupil_neo | default('no') }}"
  use_emotibit: "{{ cookiecutter.use_emotibit | default('no') }}"
  use_eeg: "{{ cookiecutter.use_eeg | default('no') }}"
  use_millikey: "{{ cookiecutter.use_millikey | default('no') }}"
  use_lsl: "{{ cookiecutter.use_lsl | default('yes') }}"

recording:
  sampling_rate_hz: {{ cookiecutter.sampling_rate }}
  duration_minutes: {{ cookiecutter.duration_minutes }}
  calibration: true
  segments:
    - label: "baseline"
      duration: 30
    - label: "stimulus"
      duration: 180
    - label: "rest"
      duration: 60

participant:
  type: human
  group: control
  age_range: adult
  language: es

tags:
  paradigm: ["attention", "fixation"]
  modality: ["eye-tracking", "physiology", "motor"]
  devices: ["pupil-core", "emotibit", "millikey"]
