[tool.poetry]
name = "{{ cookiecutter.lab_name }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author }}"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
notebook = "^7.1.1"
jupyterlab = "^4.1.5"
numpy = "^1.26.4"
pandas = "^2.2.1"
matplotlib = "^3.8.3"
scikit-learn = "^1.4.2"
mne = "^1.6.1"
neurokit2 = "^0.2.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
