[experiment]
name = "{{ cookiecutter.experiment }}"
description = "{{ cookiecutter.description }}"
author = "{{ cookiecutter.author_name }}"
version = "{{ cookiecutter.version }}"
created = "{{ cookiecutter._template_context_cookiecutter.creation_date | default('2025-04-18') }}"

[hardware]
use_pupil_labs = "{{ cookiecutter.use_pupil_labs }}"
use_emotibit = "{{ cookiecutter.use_emotibit }}"
use_eeg = "no"  # Extendible en el futuro

[recording]
sampling_rate_hz = {{ cookiecutter.sampling_rate }}
duration_minutes = {{ cookiecutter.duration_minutes }}

[paths]
data_dir = "data/"
log_dir = "log/"
scripts_dir = "scripts/"
config_dir = "config/"

[tags]
paradigm = ["attention", "fixation"]
modality = ["eye-tracking", "physiology"]

