[experiment]
name = "{{ cookiecutter.experiment }}"
description = "{{ cookiecutter.description }}"
author = "{{ cookiecutter.author_name }}"
version = "{{ cookiecutter.version }}"
created = "{{ cookiecutter._template_context_cookiecutter.creation_date | default('2025-04-18') }}"
uuid = "{{ cookiecutter._template_context_cookiecutter.experiment_id | default('autogen') }}"

[hardware]
use_pupil_core = "{{ cookiecutter.use_pupil_core | default('yes') }}"
use_pupil_neo = "{{ cookiecutter.use_pupil_neo | default('no') }}"
use_emotibit = "{{ cookiecutter.use_emotibit | default('no') }}"
use_eeg = "{{ cookiecutter.use_eeg | default('no') }}"
use_millikey = "{{ cookiecutter.use_millikey | default('no') }}"
use_lsl = "{{ cookiecutter.use_lsl | default('yes') }}"

[recording]
sampling_rate_hz = {{ cookiecutter.sampling_rate }}
duration_minutes = {{ cookiecutter.duration_minutes }}
segments = 1
calibration = true

[paths]
data_dir = "data/"
log_dir = "log/"
scripts_dir = "scripts/"
config_dir = "config/"
output_dir = "objects-output/"

[tags]
paradigm = ["attention", "fixation"]
modality = ["eye-tracking", "physiology", "motor"]
devices = ["pupil-core", "emotibit", "millikey"]

[participant]
type = "human"
group = "control"
age_range = "adult"
language = "es"
